name: Cofre Digital - Deploy Automatizado

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN_APP: ${{ secrets.TOKEN_APP }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -f app/docker/Dockerfile -t cofre-digital-app .

  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificação de segurança
        run: echo "Nenhum vazamento encontrado!"
